
version: '3'

services:
  client:
    build:
      context: ./client
    ports:
      - "5134:5134"
    networks:
      - devops-network

  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    networks:
      - devops-network

  monitoring:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "3000:3000"
    networks:
      - devops-network

  proxy:
    image: nginx:latest
    volumes:
      - ./proxyDF/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge
version: '3'

services:
  client:
    build:
      context: ./client
    ports:
      - "5134:5134"
    networks:
      - devops-network

  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    networks:
      - devops-network

  monitoring:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "3000:3000"
    networks:
      - devops-network

  proxy:
    image: nginx:latest
    volumes:
      - ./proxyDF/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge
version: '3'

services:
  client:
    build:
      context: ./client
    ports:
      - "5134:5134"
    networks:
      - devops-network

  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    networks:
      - devops-network

  monitoring:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "3000:3000"
    networks:
      - devops-network

  proxy:
    image: nginx:latest
    volumes:
      - ./proxyDF/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge
 
